force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/accountQueueableClass.cls
public class accountQueueableClass implements Queueable{
    
    public List<Account> acctsPassed;

    public accountQueueableClass(List<Account> acctList){
        acctsPassed = acctList;
    } 
    
    public void execute(QueueableContext param1){
        List<Contact> contToUpdate = new List<Contact>();
        
        for(Contact cont : [SELECT Id, Push_Date__c, Account.PushToVendor__c FROM Contact WHERE AccountId IN: acctsPassed AND Account.PushToVendor__c = 'Yes']){
            cont.Push_Date__c = Datetime.now();
            contToUpdate.add(cont);
        }
        
        for(Contact cont : [SELECT Id, Push_Date__c, Account.PushToVendor__c FROM Contact WHERE AccountId IN: acctsPassed AND Account.PushToVendor__c = 'No']){
            cont.Push_Date__c = null;
            contToUpdate.add(cont);
        }
        
        update contToUpdate;
    }
}