force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateAccContactsBatch.cls
public with sharing class UpdateAccContactsBatch implements Database.Batchable<Contact> {

    Set<Id> accIds = new Set<Id>();

    public UpdateAccContactsBatch(Set<Id> accIdsParam)
    {
        accIds = accIdsParam;
    }

    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Push_Date__c, Account.PushToVendor__c FROM Contact WHERE Account.Id IN :accIds';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<Contact> scope){

        List<Contact> conList = new List<Contact>();

        for(Contact c: scope){
            if(c.Account.PushToVendor__c == 'Yes') {c.Push_Date__c = System.now();}
            if(c.Account.PushToVendor__c == 'No') {c.Push_Date__c = null;}

            conList.add(c);
        }
        Database.update(conList,false);
    }

    public void finish(Database.BatchableContext BC){

    }
}