force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountQueuebleClass.cls
public class AccountQueuebleClass implements Queueable {
    
    private List<Contact> myList;
    public AccountQueuebleClass(List<Contact> lstParam) {
        myList = lstParam;
    }
    public void execute(QueueableContext context) {
        for(Contact con: myList){
            if(con.Account.PushToVendor__c == 'Yes'){
                con.Push_Date__c = Date.today();
            }
            else if(con.Account.PushToVendor__c == 'No'){
                con.Push_Date__c = null;
            }
        }
        update myList;       
    }
}