force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContactUpdateBatchTest.cls
@isTest
public with sharing class ContactUpdateBatchTest {
    static testmethod void ContactUpdateBatchTest() {
        // Create test accounts to be updated by batch
    List<Account> accList = new List<Account>();
    
    for (Integer i=0;i<200;i++) {
        Account account = new Account(Name = 'Account ' + i, PushToVendor__c = 'Yes');
        accList.add(account);
    }
    insert accList;

    List<Contact> conList = new List<Contact>();    

    for (Integer i=0; i<200;i++){
        Contact contact = new Contact(LastName = 'Contact ' + i, AccountId = accList[i].Id);
        conList.add(contact);
    }
    insert conList;

    Map<Id, String> lastAccountByContactsMap = new Map<Id, String>();
    for (Integer i=0;i<200;i++){
        lastAccountByContactsMap.put(conList[i].Id, accList[i].PushToVendor__c);
    }
 
    Test.startTest();
        ContactUpdateBatch batch = new ContactUpdateBatch(lastAccountByContactsMap);
        database.executeBatch(batch);
    Test.stopTest();
        // Verify contact updated
    List<Contact> conUpdatedList = [SELECT Id, Push_Date__c FROM Contact];
    System.assert(conUpdatedList[0].Push_Date__c != null);
    }
}