force-app/main/default/objects/Account/fields/Push_To_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Push_To_Vendor__c</fullName>
    <label>Push To Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateContactQueue.cls
public with sharing class UpdateContactQueue implements Queueable{
    Account accountToUpdate;
    List<Contact> contactsToUpdate;
    List<Contact> newContacts = new List<Contact>();
    public UpdateContactQueue(List<Contact> contacts, Account account) {
        this.accountToUpdate = account;
        this.contactsToUpdate = contacts;
    }

    public void execute(QueueableContext context){
        for (Contact c : contactsToUpdate){
            if (accountToUpdate.Push_To_Vendor__c == 'Yes'){
                c.Push_Date__c = System.today();
                newContacts.add(c);
            } else{
                c.Push_Date__c = Null;
                newContacts.add(c);
            }
        }

        update newContacts;
    }
}