force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PushContactHelper.cls
public inherited sharing class PushContactHelper {
    public static void updateContacts(List<Contact> contacts){
        List<Contact> toUpdate= new List<Contact>();
        for (Contact c : contacts){
            if(c.Account.PushToVendor__c == Constants.ACCOUNT_PUSH_TO_VENDOR_YES){
                c.Push_Date__c = Datetime.now();
                toUpdate.add(c);
            }
            else if(c.Account.PushToVendor__c == Constants.ACCOUNT_PUSH_TO_VENDOR_NO){
                c.Push_Date__c = null;
                toUpdate.add(c);
            }
        }
        if(!toUpdate.isEmpty())
        	update contacts;
    }
    public static void updateContacts(List<Account> accounts){
        List<Contact> contacts = [Select Id,Account.PushToVendor__c From Contact Where AccountId In :accounts];
        updateContacts(contacts);
    }
    @future
    public static void updateContactsFuture(List<Id> accountsId){
        updateContacts([Select Id From Account Where Id In :accountsId]);
    }
}