force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateContacts.cls
public without sharing class UpdateContacts {


    public static void updateCons(List<Account> accounts){
        List<Contact> contactsUpdated = new List<Contact>();
        for (Account acc : accounts) {
            if (acc.PushToVendor__c == 'Yes') {
                for(Contact con :acc.Contacts){
                    con.Push_Date__c = Datetime.now();
                    contactsUpdated.add(con);
                }
            } else if (acc.PushToVendor__c == 'No'){
                for(Contact con :acc.Contacts){
                    con.Push_Date__c = null;
                    contactsUpdated.add(con);
                } 
            }
            
        }

        update contactsUpdated;
    }
}