force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/UpdateAccContactsAsync.cls
public with sharing class UpdateAccContactsAsync {
    @future
    public static void UpdateAccContactsAsync(Set<Id> accIds) {

        List<Contact> conList = new List<Contact>();

        for(Contact c : [SELECT Id, Account.PushToVendor__C FROM Contact WHERE Account.Id IN :AccIds]){
            if(c.Account.PushToVendor__c == 'Yes') {c.Push_Date__c = now();}
            if(c.Account.PushToVender__c == 'No') {c.Push_Date__c = null;}

            conList.add(c);
        }

        //Update Async
        Database.update(conList,false);
    }
}