force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Test_AccountTriggerHandler.cls
@isTest 
private  class Test_AccountTriggerHandler {
    static testMethod void testSyncAccountUpdate() {
        Account acc = new Account(Name = 'Test Acc');
        insert acc;

        List<Contact> conList = new List<Contact>();
        for(Integer i =0; i<20; i++){
            Contact con = new Contact(FirstName = 'Test Con'+i, LastName='Tester', AccountId=acc.Id);
            conList.add(con);
        }
        insert conList;

        Test.startTest();
        acc.PushToVendor__c = 'Yes';
        update acc;
        Test.stopTest();

        System.assertEquals(20, [SELECT COUNT() FROM Contact WHERE Push_Date__c != null]);
    }

    static testMethod void testAsyncAccountUpdate() {
        Account acc = new Account(Name = 'Test Acc');
        insert acc;

        List<Contact> conList = new List<Contact>();
        for(Integer i =0; i<210; i++){
            Contact con = new Contact(FirstName = 'Test Con'+i, LastName='Tester', AccountId=acc.Id);
            conList.add(con);
        }
        insert conList;

        Test.startTest();
        acc.PushToVendor__c = 'Yes';
        update acc;
        Test.stopTest();

        System.assertEquals(210, [SELECT COUNT() FROM Contact WHERE Push_Date__c != null]);
    }
}