force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QueueableUpdateContact.cls
public with sharing class QueueableUpdateContact implements Queueable{
    private Set<Id> accountsIds = new Set<Id>();
    public QueueableUpdateContact(Set<Id> accountsId) {
        this.accountsIds = accountsId;
    }

    public void execute(QueueableContext context) { 
        //UpdateContacts.updateCons(this.accountContactsToUpdate);
        List<Contact> contactsUpdated = new List<Contact>([SELECT Id, Account.PushToVendor__c FROM Contact WHERE AccountId IN:accountsIds]);
        for (Contact con : contactsUpdated) {
            if (con.Account.PushToVendor__c == 'Yes') {  
                con.Push_Date__c = Datetime.now();
            } else if (con.Account.PushToVendor__c == 'No'){
                con.Push_Date__c = null;
            }
            
        }

        update contactsUpdated;
    }
}