force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountBatchUpdate.cls
public class AccountBatchUpdate implements Database.batchable<sObject>, Database.Stateful{ 

    public List<SObject> accounts;

    public AccountBatchUpdate(List<SObject> accounts){      
        this.accounts = accounts;
    }
    public List<SObject> start(Database.BatchableContext BC)
    {
        return[SELECT Id,AccountId,Push_Date__c,Account.PushToVendor__c FROM Contact WHERE AccountId IN :accounts];
    }
    
    public void execute(Database.BatchableContext BC, List<Contact> scope)
    {
        System.debug('enter to execute');
        List<Contact> contactsToUpdate = new List<Contact>();
        for(Contact c: scope){
            if(string.isNotBlank(c.Account.PushToVendor__c)){
                if(c.Account.PushToVendor__c=='Yes'){
                    c.Push_Date__c = date.today();
                }
                else if(c.Account.PushToVendor__c=='No'){
                    c.Push_Date__c = null;         
                }
                contactsToUpdate.add(c);
            }
        }
        update contactsToUpdate;
    
    }
    
    public void finish(Database.BatchableContext BC)
    {
    }
}