force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public with sharing class AccountHandler {
    public static void updateContacts(List<Account> acclist){

        List<Contact> consToUpdate = [Select Id, Push_Date__c, Account.PushToVendor__c FROM Contact WHERE AccountId in :acclist];
        
        for(Contact con: consToUpdate){
            if(con.Account.PushToVendor__c == 'Yes'){
                con.Push_Date__c = Date.today();
            }
            else if(con.Account.PushToVendor__c == 'No'){
                con.Push_Date__c = null;
            }
        }

        if(consToUpdate.size() <= 200 && consToUpdate.size() > 0){
           
            update consToUpdate;

        } else if (consToUpdate.size()<= 1000){
            ID jobID = System.enqueueJob(new AccountQueuebleClass(consToUpdate));
        }
        
        else if(consToUpdate.size()> 1000){   
            ID batch = Database.executeBatch(new AccountBatchClass(consToUpdate), 150);
        }


    }

}