force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Test_UpdateContactsBatchable.cls
@isTest
private with sharing class Test_UpdateContactsBatchable {
    @isTest
    static void updateContactsBatchableOverTest() {
        TestDataFactory.initData(2, 20);
        List<Contact> contactList = [SELECT Id, Push_Date__c, Account.PushToVendor__c
                                     FROM Contact 
                                     WHERE Account.PushToVendor__c = 'YES'];
        system.assertNotEquals(System.today(), contactList[0].Push_Date__c);
        UpdateContactsBatchable batch = new UpdateContactsBatchable(contactList);
        Test.startTest();
        Id jobid = Database.executeBatch(batch,150);
        Test.stopTest();
        
        contactList = [SELECT Id, Push_Date__c, Account.PushToVendor__c
                        FROM Contact 
                        WHERE Account.PushToVendor__c = 'YES'];

        System.assertEquals(System.today(), contactList[0].Push_Date__c);
    }
}