force-app/main/default/objects/Account/fields/PushtoVendor__c.field-meta.xml
<CustomField>
    <fullName>PushtoVendor__c</fullName>
    <label>Push to Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_Date__c.field-meta.xml
<CustomField>
    <fullName>Push_Date__c</fullName>
    <defaultValue>NULL</defaultValue>
    <label>Push Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BatchContactUpdate.cls
public with sharing class BatchContactUpdate implements Database.Batchable<sObject> {
    Set<Id> accIdsUpdated = new Set<Id>();
    public BatchContactUpdate(SET<Id> accIdsToUpdate) {
        accIdsUpdated = accIdsToUpdate;
    }

    public Database.QueryLocator start(Database.BatchableContext bc){
        System.debug('accIdsUpdated----'+accIdsUpdated);
        return Database.getQueryLocator([SELECT Id, Push_Date__c, Account.PushToVendor__c, AccountId FROM Contact WHERE AccountId IN: accIdsUpdated]);
    }

    public void execute(Database.BatchableContext bc, List<Contact> scope){
        for(Contact con: scope){
            con.Push_Date__c = con.Account.PushToVendor__c == 'Yes' ? System.today() : null;
        }

        if(!scope.isEmpty() && Schema.sObjectType.Contact.isUpdateable()){
            update scope;
        }
    }

    public void finish(Database.BatchableContext bc){
    }
}